name: moli
favicon: null
layout_spectrum: 0.5425522730220109
typography_spectrum: 0.029765944462269545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6253978183958679
  lightness: 0.911208804929629
  saturation: 0.9971241450402886
  rhythmicContrast: 0.2537544590886682
purpose: []
