name: moli
favicon: null
layout_spectrum: 0.98806
typography_spectrum: 0.33441
title: MOLI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d4d21'
    - '#251b0d'
    - '#eca441'
    - '#ffffff'
    - '#868073'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
